version: "3.8"

services:
  portfolio:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: portfolio:latest
    container_name: portfolio
    volumes:
      - ./:/var/www:rw
    tty: true
    command: "symfony server:start --port=80"
    labels:
      - traefik.http.routers.portfolio.rule=Host(`melaine-gerard.fr`)
      - traefik.http.routers.portfolio.tls=true
      - traefik.http.routers.portfolio.tls.certresolver=lets-encrypt
      - traefik.port=80
      - "traefik.enable=true"
    networks:
      - local
    restart: unless-stopped
networks:
  local:
    name: local
    external: true